---
title: TAPS Economic Questions
author: JBrandon Duck-Mayr
output:
    md_document:
        variant: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
quack::attach_common_packages()
```

# TAPS Economic Questions

From December 2011 to January 2018, the [Weidenbaum Center on the Economy, Government, and Public Policy](https://wc.wustl.edu/) at [Washington University in St. Louis](https://wustl.edu/) ran [The American Panel Survey](https://wc.wustl.edu/american-panel-survey) (TAPS), a monthly survey revisiting the same nationally representative panel of respondents.
Among the recurring sets of questions asked of respondents were the following questions about the economy (with observed answer choices underneath each question):

- ECON1A: [in your household] Are the economic conditions in your household and in the countryare getting better, worse, or not changing much?
  - Refused
  - Getting much better
  - Getting somewhat better
  - Not changing much
  - Getting somewhat worse
  - Getting much worse
  - Not sure
- ECON1B: [In the country as a whole] Are the economic conditions in your household and in the countryare getting better, worse, or not changing much?
  - Refused
  - Getting much better
  - Getting somewhat better
  - Not changing much
  - Getting somewhat worse
  - Getting much worse
  - Not sure
- ECON2A: [In your household] Are the current economic conditions in your household and in the country excellent, good, only fair, or poor?
  - Refused
  - Excellent
  - Good
  - Only fair
  - Poor
  - Not sure
- ECON2B: [In the country as a whole] Are the current economic conditions in your household and in the country excellent, good, only fair, or poor?
  - Refused
  - Excellent
  - Good
  - Only fair
  - Poor
  - Not sure
- ECON4A: [I expect to spend...] Compared to what you have done in the past few months, do you expect to spend or save
  - Refused
  - Much more
  - More
  - About the same
  - Less
  - Much less
- ECON4B: [I expect to save...] Compared to what you have done in the past few months, do you expect to spend or save
  - Refused
  - Much more
  - More
  - About the same
  - Less
  - Much less
